name: rrc
favicon: null
layout_spectrum: 0.6989477328024805
typography_spectrum: 0.006249583326280117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7147219444159418
  lightness: 0.4336045414675027
  saturation: 0.8919461271725595
  rhythmicContrast: 0.7480136097874492
purpose: []
